"""Portable runtime primitives for public RAGFlow skills."""

from .auth import AuthError, load_api_key
from .config import (
    ConfigError,
    DocToMdConfig,
    MineruConfig,
    RagflowConfig,
    SkillConfig,
    load_config,
    load_skill_config,
)
from .doc_convert import (
    ConvertedDocument,
    DocConvertError,
    SourceDocument,
    convert_source_to_markdown,
    discover_source_documents,
    extract_markdown_title,
    html_to_markdown,
    make_doc_manifest_payload,
    safe_markdown_name,
    sha256_file,
    text_to_markdown,
)
from .doc_quality import (
    BLOCKED,
    PASS,
    PASS_WITH_REVIEW,
    DocQualityError,
    QualityDocument,
    QualityDocumentReport,
    QualityIssue,
    inspect_quality_document,
    load_doc_manifest_payload,
    make_quality_report_payload,
    quality_documents_from_manifest,
    render_quality_markdown,
)
from .doc_segment import (
    DEFAULT_HARD_MAX_CHARS,
    DEFAULT_MIN_SEGMENT_CHARS,
    DEFAULT_SOFT_MAX_CHARS,
    DocSegmentError,
    DocumentSegment,
    MaterializedSegments,
    SegmentationPlan,
    materialize_segments,
    plan_markdown_segmentation,
)
from .diagnostics import (
    DIAGNOSTIC_REPORT_SCHEMA,
    DiagnosticIssue,
    diagnose_kb_manifest,
    probe_ragflow_client,
    render_diagnostic_markdown,
)
from .manifests import (
    DocManifest,
    DocumentEntry,
    KbDataset,
    KbDocumentEntry,
    KbManifest,
    ManifestError,
    load_doc_manifest,
    load_kb_manifest,
)
from .ragflow_client import RAGFlowClient
from .profiles import ChunkProfile, ProfileError, load_profile
from .kb_build import (
    BuildDocument,
    BuildError,
    discover_markdown_documents,
    extract_document_id,
    extract_document_items,
    extract_document_name,
    extract_document_states,
    make_kb_manifest_payload,
    normalize_document_state,
    wait_for_document_states,
)
from .retrieval import (
    NormalizedChunk,
    QueryResult,
    RetrievalError,
    normalize_retrieval_response,
    resolve_dataset_ids,
)
from .validation import (
    ValidationCaseResult,
    ValidationError,
    ValidationQuery,
    ValidationReport,
    evaluate_query_result,
    load_validation_queries,
    render_markdown_report,
    run_retrieval_validation,
    smoke_query,
)

__all__ = [
    "AuthError",
    "BLOCKED",
    "ConfigError",
    "DEFAULT_HARD_MAX_CHARS",
    "DEFAULT_MIN_SEGMENT_CHARS",
    "DEFAULT_SOFT_MAX_CHARS",
    "DIAGNOSTIC_REPORT_SCHEMA",
    "DiagnosticIssue",
    "DocManifest",
    "DocToMdConfig",
    "ConvertedDocument",
    "DocConvertError",
    "DocQualityError",
    "DocSegmentError",
    "DocumentEntry",
    "DocumentSegment",
    "KbDataset",
    "KbDocumentEntry",
    "KbManifest",
    "ManifestError",
    "MaterializedSegments",
    "MineruConfig",
    "PASS",
    "PASS_WITH_REVIEW",
    "ChunkProfile",
    "ProfileError",
    "QualityDocument",
    "QualityDocumentReport",
    "QualityIssue",
    "RAGFlowClient",
    "RagflowConfig",
    "SegmentationPlan",
    "SkillConfig",
    "SourceDocument",
    "BuildDocument",
    "BuildError",
    "NormalizedChunk",
    "QueryResult",
    "RetrievalError",
    "ValidationCaseResult",
    "ValidationError",
    "ValidationQuery",
    "ValidationReport",
    "convert_source_to_markdown",
    "diagnose_kb_manifest",
    "discover_markdown_documents",
    "discover_source_documents",
    "extract_markdown_title",
    "extract_document_id",
    "extract_document_items",
    "extract_document_name",
    "extract_document_states",
    "evaluate_query_result",
    "html_to_markdown",
    "inspect_quality_document",
    "load_doc_manifest_payload",
    "make_kb_manifest_payload",
    "make_doc_manifest_payload",
    "make_quality_report_payload",
    "materialize_segments",
    "plan_markdown_segmentation",
    "probe_ragflow_client",
    "quality_documents_from_manifest",
    "load_api_key",
    "load_config",
    "load_skill_config",
    "load_doc_manifest",
    "load_kb_manifest",
    "load_profile",
    "load_validation_queries",
    "normalize_retrieval_response",
    "normalize_document_state",
    "resolve_dataset_ids",
    "render_diagnostic_markdown",
    "render_quality_markdown",
    "render_markdown_report",
    "run_retrieval_validation",
    "safe_markdown_name",
    "sha256_file",
    "smoke_query",
    "text_to_markdown",
    "wait_for_document_states",
]

__version__ = "0.1.0"
